const cfg=window.AGROQUIZ_CONFIG||{};
const db=(cfg.supabaseUrl&&cfg.supabaseAnonKey)?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey):null;
let QUESTIONS=[],session=null,player=null,channel=null,timer=null,selectedTopics=[];
const app=document.querySelector('#app');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const configured=()=>!!db;
async function loadQuestions(){QUESTIONS=await fetch('questions.json').then(r=>r.json())}
function shell(html){app.innerHTML=`<main class="wrap"><div class="topbar"><div class="brand">Agro<span>Quiz</span></div><button class="secondary" onclick="home()">Inicio</button></div>${html}<div class="footer">Agricultura · aprendizaje basado en datos</div></main>`}
function home(){clearInterval(timer);if(channel&&db)db.removeChannel(channel);channel=null;session=null;player=null;app.innerHTML=`<main class="wrap hero"><section class="card hero-card"><div class="brand">Agro<span>Quiz</span></div><div class="eyebrow">Agricultura y tecnología</div><h1>Aprender.<br>Responder.<br>Aplicar.</h1><p class="muted">Preguntas en vivo para convertir la clase en una conversación basada en evidencia.</p>${!configured()?'<div class="notice">Modo de configuración: falta conectar Supabase para habilitar sesiones entre varios dispositivos.</div>':''}<div class="actions"><button onclick="teacherSetup()">Soy docente</button><button class="secondary" onclick="studentJoin()">Soy estudiante</button></div></section></main>`}
function teacherSetup(){let topics=[...new Set(QUESTIONS.map(q=>q.topic))];shell(`<section class="grid"><div class="card"><div class="eyebrow">Nueva actividad</div><h2>Crear sesión</h2><div class="field"><label>Título</label><input id="title" value="GNSS y RTK · Cosecha mecanizada"></div><div class="field"><label>Número de preguntas</label><select id="count"><option>5</option><option>10</option><option selected>15</option><option>18</option></select></div><div class="field"><label>Temas</label><div class="topics">${topics.map((t,i)=>`<label class="topic"><input type="checkbox" value="${esc(t)}" ${t==='GNSS y RTK · Cosecha mecanizada'?'checked':''}> ${esc(t)}</label>`).join('')}</div></div><button onclick="createSession()">Crear sala</button></div><div class="card"><div class="eyebrow">Modo clase</div><h2>Tú controlas el ritmo</h2><p>Los estudiantes entran por PIN o QR. Tú lanzas la pregunta, observas respuestas y decides cuándo revelar la correcta.</p><p class="muted">El puntaje combina acierto y rapidez. La explicación aparece después de revelar la respuesta.</p></div></section>`)}
async function createSession(){if(!configured())return alert('Primero debemos conectar Supabase.');selectedTopics=[...document.querySelectorAll('.topic input:checked')].map(x=>x.value);let pool=QUESTIONS.filter(q=>selectedTopics.includes(q.topic)).sort(()=>Math.random()-.5);let n=+document.querySelector('#count').value;let ids=pool.slice(0,n).map(q=>q.id);let pin=String(Math.floor(100000+Math.random()*900000));let title=document.querySelector('#title').value.trim()||'AgroQuiz';let {data,error}=await db.from('sessions').insert({pin,title,question_ids:ids}).select().single();if(error)return alert(error.message);session=data;teacherLobby()}
async function refreshPlayers(){if(!session)return[];let {data}=await db.from('players').select('*').eq('session_id',session.id).order('joined_at');return data||[]}
async function teacherLobby(){let ps=await refreshPlayers();let join=`${location.origin}${location.pathname}?pin=${session.pin}`;shell(`<section class="lobby"><div class="card"><div class="eyebrow">PIN de juego</div><div class="pin">${session.pin}</div><div id="qr" class="qr"></div><p class="muted">Escanea para entrar directamente.</p></div><div class="card"><div class="eyebrow">Sala de espera</div><h2>${esc(session.title)}</h2><p><b id="pc">${ps.length}</b> participantes conectados</p><div id="players" class="players">${ps.map(p=>`<span class="chip">${esc(p.name)}</span>`).join('')}</div><div class="actions" style="justify-content:flex-start"><button onclick="startQuiz()" ${ps.length?'':'disabled'}>Comenzar</button></div></div></section>`);new QRCode(document.querySelector('#qr'),{text:join,width:190,height:190});subscribeTeacherLobby()}
function subscribeTeacherLobby(){if(channel)db.removeChannel(channel);channel=db.channel('teacher-'+session.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'players',filter:`session_id=eq.${session.id}`},async()=>{let ps=await refreshPlayers();document.querySelector('#pc').textContent=ps.length;document.querySelector('#players').innerHTML=ps.map(p=>`<span class="chip">${esc(p.name)}</span>`).join('')}).subscribe()}
async function startQuiz(){await db.from('sessions').update({status:'question',current_index:0,question_started_at:new Date().toISOString()}).eq('id',session.id);await loadSession();teacherQuestion()}
async function loadSession(){let {data}=await db.from('sessions').select('*').eq('id',session.id).single();session=data}
function currentQ(){return QUESTIONS.find(q=>q.id===session.question_ids[session.current_index])}
async function teacherQuestion(){clearInterval(timer);let q=currentQ();let ps=await refreshPlayers();shell(`<section class="card"><div class="topbar"><div><span class="eyebrow">Pregunta ${session.current_index+1} de ${session.question_ids.length}</span><div>${esc(q.topic)}</div></div><div class="timer" id="timer">30</div></div><div class="question">${esc(q.question)}</div><div class="answers">${q.options.map((o,i)=>`<div class="answer"><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</div>`).join('')}</div><div class="stats"><div class="stat"><b id="answered">0</b>respondieron</div><div class="stat"><b>${ps.length}</b>jugadores</div><div class="stat"><b id="remaining">30</b>segundos</div></div><div class="actions"><button onclick="reveal()">Revelar respuesta</button></div></section>`);let left=30;timer=setInterval(()=>{left--;let a=document.querySelector('#timer'),b=document.querySelector('#remaining');if(a)a.textContent=left;if(b)b.textContent=left;if(left<=0){clearInterval(timer);reveal()}},1000);subscribeAnswers()}
function subscribeAnswers(){if(channel)db.removeChannel(channel);channel=db.channel('answers-'+session.id).on('postgres_changes',{event:'INSERT',schema:'public',table:'answers',filter:`session_id=eq.${session.id}`},async()=>{let q=currentQ();let {count}=await db.from('answers').select('*',{count:'exact',head:true}).eq('session_id',session.id).eq('question_id',q.id);let el=document.querySelector('#answered');if(el)el.textContent=count||0}).subscribe()}
async function reveal(){clearInterval(timer);await db.from('sessions').update({status:'reveal'}).eq('id',session.id);await loadSession();let q=currentQ();let {data:ans}=await db.from('answers').select('*').eq('session_id',session.id).eq('question_id',q.id);let counts=q.options.map((_,i)=>(ans||[]).filter(a=>a.option_index===i).length);shell(`<section class="card"><div class="eyebrow">Resultado</div><div class="question">${esc(q.question)}</div><div class="answers">${q.options.map((o,i)=>`<div class="answer ${i===q.correct?'correct':''}"><b>${String.fromCharCode(65+i)}.</b> ${esc(o)} <span style="float:right">${counts[i]}</span></div>`).join('')}</div><div class="explanation"><b>¿Por qué?</b><br>${esc(q.explanation)}</div><div class="actions"><button onclick="nextQuestion()">${session.current_index+1<session.question_ids.length?'Siguiente pregunta':'Ver podio'}</button></div></section>`)}
async function nextQuestion(){if(session.current_index+1>=session.question_ids.length){await db.from('sessions').update({status:'finished'}).eq('id',session.id);return podium()}await db.from('sessions').update({status:'question',current_index:session.current_index+1,question_started_at:new Date().toISOString()}).eq('id',session.id);await loadSession();teacherQuestion()}
async function podium(){let ps=await refreshPlayers();ps.sort((a,b)=>b.score-a.score);shell(`<section class="card"><div class="eyebrow">Sesión finalizada</div><h1>🏆 Podio AgroQuiz</h1><div class="ranking">${ps.map((p,i)=>`<div class="rank"><span><b>${i+1}.</b> ${esc(p.name)}</span><b>${p.score} pts</b></div>`).join('')}</div><div class="actions"><button onclick="teacherSetup()">Nueva sesión</button></div></section>`)}
function studentJoin(){let preset=new URLSearchParams(location.search).get('pin')||'';shell(`<section class="card" style="max-width:560px;margin:auto"><div class="eyebrow">Entrar a una clase</div><h2>Únete a AgroQuiz</h2>${!configured()?'<div class="notice">La conexión en tiempo real aún no está configurada.</div>':''}<div class="field"><label>PIN</label><input id="pin" inputmode="numeric" maxlength="6" value="${esc(preset)}" placeholder="123456"></div><div class="field"><label>Tu nombre</label><input id="name" maxlength="30" placeholder="Ej. Andrea"></div><button onclick="joinSession()">Entrar</button></section>`)}
async function joinSession(){if(!configured())return alert('La sala todavía no está conectada a Supabase.');let pin=document.querySelector('#pin').value.trim(),name=document.querySelector('#name').value.trim();if(!name)return alert('Escribe tu nombre.');let {data:s,error}=await db.from('sessions').select('*').eq('pin',pin).neq('status','finished').maybeSingle();if(error||!s)return alert('No encontré una sesión activa con ese PIN.');session=s;let {data:p,error:pe}=await db.from('players').insert({session_id:s.id,name}).select().single();if(pe)return alert(pe.message.includes('duplicate')?'Ese nombre ya está en la sala. Usa otro.':pe.message);player=p;studentWaiting();subscribeStudent()}
function subscribeStudent(){if(channel)db.removeChannel(channel);channel=db.channel('student-'+session.id+'-'+player.id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'sessions',filter:`id=eq.${session.id}`},payload=>{let oldStatus=session.status,oldIndex=session.current_index;session=payload.new;if(session.status==='question'&&(oldStatus!=='question'||oldIndex!==session.current_index))studentQuestion();else if(session.status==='reveal'&&oldStatus!=='reveal')studentReveal();else if(session.status==='finished')studentFinish()}).subscribe()}
function studentWaiting(){shell(`<section class="card" style="max-width:620px;margin:auto;text-align:center"><div class="eyebrow">Estás dentro</div><h1>Hola, ${esc(player.name)} 👋</h1><p class="muted">Espera a que el docente inicie la actividad.</p><div class="pin">${session.pin}</div></section>`)}
function studentQuestion(){let q=currentQ();shell(`<section class="card"><div class="eyebrow">${esc(q.topic)}</div><div class="question">${esc(q.question)}</div><div class="answers">${q.options.map((o,i)=>`<button class="answer" onclick="submitAnswer(${i},this)"><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</button>`).join('')}</div><p id="msg" class="muted">Selecciona una respuesta.</p></section>`)}
async function submitAnswer(i,btn){document.querySelectorAll('.answer').forEach(x=>x.disabled=true);btn.classList.add('selected');let q=currentQ();let elapsed=Math.max(0,(Date.now()-new Date(session.question_started_at).getTime())/1000);let correct=i===q.correct;let points=correct?Math.round(600+400*Math.max(0,(30-elapsed)/30)):0;let {error}=await db.from('answers').insert({session_id:session.id,player_id:player.id,question_id:q.id,option_index:i,is_correct:correct,points});if(error){document.querySelector('#msg').textContent='No pude registrar la respuesta.';return}if(points){player.score+=points;await db.from('players').update({score:player.score}).eq('id',player.id)}document.querySelector('#msg').textContent='Respuesta registrada. Espera a que el docente revele el resultado.'}
async function studentReveal(){let q=currentQ();let {data:a}=await db.from('answers').select('*').eq('player_id',player.id).eq('question_id',q.id).maybeSingle();shell(`<section class="card"><div class="eyebrow">Respuesta</div><div class="question">${a?.is_correct?'¡Correcto! 🎯':'Seguimos aprendiendo 🌱'}</div><div class="answers">${q.options.map((o,i)=>`<div class="answer ${i===q.correct?'correct':(a&&i===a.option_index?'wrong':'')}"><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</div>`).join('')}</div><div class="explanation">${esc(q.explanation)}</div><div class="stats"><div class="stat"><b>${a?.points||0}</b>esta pregunta</div><div class="stat"><b>${player.score}</b>puntaje</div></div><p class="muted">Espera la siguiente pregunta.</p></section>`)}
async function studentFinish(){let {data:p}=await db.from('players').select('*').eq('session_id',session.id).order('score',{ascending:false});let pos=(p||[]).findIndex(x=>x.id===player.id)+1;shell(`<section class="card" style="max-width:650px;margin:auto;text-align:center"><div class="eyebrow">Final</div><h1>Terminaste 🌱</h1><div class="pin">#${pos}</div><h2>${player.score} puntos</h2><p class="muted">Tu posición final en esta sesión.</p></section>`)}
loadQuestions().then(()=>{new URLSearchParams(location.search).get('pin')?studentJoin():home()}).catch(e=>{app.textContent='No se pudo cargar el banco de preguntas.';console.error(e)});
